name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: make MTerm_test
      run: make MTerm_test
    - name: start MTerm_test
      run: ./MTerm_test
      
    - name: make PrimeI_test
      run: make PrimeI_test
    - name: start PrimeI_test
      run: ./PrimeI_test
