name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: make
    - name: start
      run: ./main
